[project]
name = "bot-instagram-yt-dlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "browsercookie>=0.8.1",
    "dotenv>=0.9.9",
    "python-telegram-bot>=22.3",
    "yt-dlp>=2025.7.21",
]
